import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
} from '@clerk/nextjs'
import Navibar from "@/components/Navibar";
// 引入后端控制组件
import QueryClientProvider from "@/components/QueryClientProvider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: 'swap', // 添加 display 选项
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: 'swap', // 添加 display 选项
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const bodyClassName = `${geistSans.variable} ${geistMono.variable} antialiased flex flex-row`;

  return (
    <ClerkProvider>
      <QueryClientProvider>
        <html lang="en">
          <body className={bodyClassName}>
            <div className="w-1/5 h-screen bg-gray-50">
              <Navibar a="123" />
            </div>
            <div className="w-4/5 h-screen">
              {children}
            </div>
          </body>
        </html>
      </QueryClientProvider>
    </ClerkProvider>
  );
}